- alias: 'Turn All Lights On'
  trigger:
    platform: state
    entity_id: input_boolean.all_lights_on
    to: 'on'
  action:
    - service: light.turn_on
      entity_id: all
    - service: input_boolean.turn_off
      entity_id: input_boolean.all_lights_on


- alias: 'Turn All Lights Off'
  trigger:
    platform: state
    entity_id: input_boolean.all_lights_off
    to: 'on'
  action:
    - service: light.turn_off
      entity_id: all
    - delay: 00:00:10
    - service: input_boolean.turn_off
      entity_id: input_boolean.all_lights_off


- alias: Turn On Theater Mode
  trigger:
    platform: state
    entity_id: input_boolean.theater_mode
    to: 'on'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.theater_mode
        transition: 2.5
    - delay: 00:00:10
    - service: input_boolean.turn_off
      entity_id: input_boolean.theater_mode
